FROM node:20-alpine

ARG WORKDIR=/app
WORKDIR $WORKDIR

# Prepare the environment
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# We need only strapi dependencies which are contained in ./portal
COPY ./package.json ./
COPY ./package-lock.json ./
# Note: NODE_ENV=production is set to avoid installing devDependencies,
#  npm i installs only (production) dependencies
RUN npm i --legacy-peer-deps

# We need only strapi which is contained in ./portal
COPY ./config /app/config
COPY ./public /app/public

EXPOSE 1337

# For debugging; uncomment below to run indefinitely without errors
# CMD ["tail", "-f", "/dev/null"]

# Original command
CMD ["npm", "start"]